// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERPDemoAPI.Models;

public partial class Company
{
    [Key]
    public int Id { get; set; }

    public string CompanyName { get; set; }

    public string Street { get; set; }

    public int? PostalCode { get; set; }

    public string City { get; set; }

    public string Country { get; set; }

    public string CountryCode { get; set; }

    public string Telephone { get; set; }

    public string Email { get; set; }
}