// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERPDemoAPI.Models;

public partial class Company
{
    [Key]
    public int Id { get; set; }

    public string Firma { get; set; }

    public string Straße { get; set; }

    public int? Postleitzahl { get; set; }

    public string Ort { get; set; }

    public string Land { get; set; }

    [Column("LandISOCode")]
    public string LandIsocode { get; set; }

    public string Telefonnummer { get; set; }

    [Column("EMail")]
    public string Email { get; set; }
}